version: '1'

services:
  oogiri-frontpage-next:
    image: oogiri-frontpage:staging
    ports:
      - '4201:4200'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_VAR: uat
