version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run: yarn install

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $VM_SSH_FINGERPRINT
      - run:
          name: Deploy to GCP Compute Engine
          command: |
            ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "cd /home/dino_wu/oogiri-frontpage-next/ && sudo git pull && sudo rm -r .next && sudo yarn install && sudo yarn build:uat:local && sudo pm2 restart 14"

  production_deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $PROD_VM_SSH_FINGERPRINT
      - run:
          name: Deploy to GCP Compute Engine
          command: |
            ssh -o StrictHostKeyChecking=no $VM_USER@$PROD_VM_IP "cd /home/dino_wu/oogiri-frontpage-next/ && sudo git pull && sudo rm -r .next && sudo yarn install && sudo yarn build:prod && sudo pm2 restart jp-frontpage"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: uat
      - production_deploy:
          requires:
            - build
          filters:
            branches:
              only: main
